export enum UpdateUsernameActionTypes {
    UPDATE_USERNAME_REQUEST = 'UPDATE_USERNAME_REQUEST',
    UPDATE_USERNAME_SUCCESS = 'UPDATE_USERNAME_SUCCESS',
    UPDATE_USERNAME_ERROR = 'UPDATE_USERNAME_ERROR',

    UPDATE_USERNAME_DEFAULT_SETTINGS = 'UPDATE_USERNAME_DEFAULT_SETTINGS'
}